### ISSUE TITLE
Steps on building a physical robot

### ISSUE THREAD

**Issue by ZerothQAQ** [tomasvr/turtlebot3_drlnav#17]
I have some questions about physical bot deployment, can you put out a detailed tutorial on physical bot deployment?

**Comment by tomasvr** [comment]
I have written a section with general instructions on how to deploy models on a physical robot [here](https://github.com/tomasvr/turtlebot3_drlnav?tab=readme-ov-file#physical-robot). More detailed instructions are very dependent on the type of robot that you are using so I cannot be of much help there. Other people have created good tutorials on how to use LIDAR with ROS and physical robots, so I would suggest you search for those. Good luck!

**Comment by ZerothQAQ** [comment]
Thank you for your previous reply, but my question is I am using the real turtlebot3, if I want to deploy to it do I need to recreate a workspace on top of it and then add the operational packages about turtlebot3 and this github repository to it, or do I need to write a new script to read the trained models and then subscribe to the individual topics? Which would be better?

**Comment by ZerothQAQ** [comment]
Thanks for the answer, I have a new problem now.
When I run the model in the solid robot I get the following error.
$ ros2 run turtlebot3_drl real_agent dqn "dqn_0_stage_1" 4000
Make sure to launch the gazebo simulation node first!}
gpu torch available:  True
device name:  NVIDIA GeForce RTX 2070 with Max-Q Design
Traceback (most recent call last):
  File "/home/liangli/qdn/turtlebot3_drlnav/install/turtlebot3_drl/lib/turtlebot3_drl/real_agent", line 11, in <module>
    load_entry_point('turtlebot3-drl==2.0.0', 'console_scripts', 'real_agent')()
  File "/home/liangli/qdn/turtlebot3_drlnav/install/turtlebot3_drl/lib/python3.8/site-packages/turtlebot3_drl/drl_agent/drl_agent.py", line 215, in main_real
    main(args)
  File "/home/liangli/qdn/turtlebot3_drlnav/install/turtlebot3_drl/lib/python3.8/site-packages/turtlebot3_drl/drl_agent/drl_agent.py", line 200, in main
    drl_agent = DrlAgent(*args)
  File "/home/liangli/qdn/turtlebot3_drlnav/install/turtlebot3_drl/lib/python3.8/site-packages/turtlebot3_drl/drl_agent/drl_agent.py", line 58, in __init__
    print(f"{'training' if (self.training) else 'testing' } on stage: {util.stage}")
AttributeError: module 'turtlebot3_drl.common.utilities' has no attribute 'stage

**Comment by ZerothQAQ** [comment]
Ok, I've figured out how to do this now, but I have a small query about ros2 which is how to limit the number of real radar samples received to match the number of radar samples during training
