### ISSUE TITLE
No such file or directory: '/tmp/drlnav_current_stage.txt'

### ISSUE THREAD

**Issue by dokyun-kim4** [tomasvr/turtlebot3_drlnav#27]
Hi, I am trying to run the `ros2 run turtlebot3_drl gazebo_goals` in the docker environment and I am getting the following error message:  

```
Traceback (most recent call last):
  File "/home/turtlebot3_drlnav/install/turtlebot3_drl/lib/turtlebot3_drl/gazebo_goals", line 11, in <module>
    load_entry_point('turtlebot3-drl==2.0.0', 'console_scripts', 'gazebo_goals')()
  File "/home/turtlebot3_drlnav/install/turtlebot3_drl/lib/python3.8/site-packages/turtlebot3_drl/drl_gazebo/drl_gazebo.py", line 263, in main
    drl_gazebo = DRLGazebo()
  File "/home/turtlebot3_drlnav/install/turtlebot3_drl/lib/python3.8/site-packages/turtlebot3_drl/drl_gazebo/drl_gazebo.py", line 54, in __init__
    with open('/tmp/drlnav_current_stage.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/drlnav_current_stage.txt'
```
Is this something that I need to create myself?

**Comment by Sanidhya-30** [comment]
Were you running the Gazebo GUI in another terminal?
using any of the launch scripts, like:
ros2 launch turtlebot3_gazebo turtlebot3_drl_stage5.launch.py

**Comment by chengjie-lu** [comment]
Hi, I also have the same problem. did you resolve this issue?

**Comment by Sanidhya-30** [comment]
I remember trying by creating an empty file with same name, did you add any content to the file?
Would be awesome if you could share.

**Comment by chengjie-lu** [comment]
> I remember trying by creating an empty file with same name, did you add any content to the file? Would be awesome if you could share.

you can put a number from 1 - 10.
