### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by PUNLEUR13335** [tomasvr/turtlebot3_drlnav#28]
punleur@hoverbot:~/3_turtlebot3_drlnav$ ros2 run turtlebot3_drl gazebo_goals
Traceback (most recent call last):
  File "/home/punleur/3_turtlebot3_drlnav/install/turtlebot3_drl/lib/turtlebot3_drl/gazebo_goals", line 33, in <module>
    sys.exit(load_entry_point('turtlebot3-drl==2.0.0', 'console_scripts', 'gazebo_goals')())
  File "/home/punleur/3_turtlebot3_drlnav/install/turtlebot3_drl/lib/python3.10/site-packages/turtlebot3_drl/drl_gazebo/drl_gazebo.py", line 263, in main
    drl_gazebo = DRLGazebo()
  File "/home/punleur/3_turtlebot3_drlnav/install/turtlebot3_drl/lib/python3.10/site-packages/turtlebot3_drl/drl_gazebo/drl_gazebo.py", line 51, in __init__
    self.entity = open(self.entity_path, 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/punleur/3_turtlebot3_drlnav/install/turtlebot3_drl/lib/python3.10/site-packages/turtlebot3_drl/drl_gazebo/model.sdf'
[ros2run]: Process exited with failure 1

**Comment by RDaneelOlivav** [comment]
Yes, this happens because at leats in humble python is 3.10, therefore we won't find the 3.8 that has to be replaced and get the path wrong. 

You hav eto replace the code in ' ~/turtlebot3_drlnav/src/turtlebot3_drl/turtlebot3_drl/drl_gazebo/drl_gazebo.py', aroudn line 48 to this:


`"""************************************************************
        ** Initialise variables
        ************************************************************"""
        # Get the base directory
        base_dir = os.path.dirname(os.path.realpath(__file__))
        print(f"base_dir path: {base_dir}")

        # Replace or modify the path dynamically
        self.entity_dir_path = base_dir.replace(
            'turtlebot3_drl/lib/python3.10/site-packages/turtlebot3_drl/drl_gazebo',
            'turtlebot3_gazebo/share/turtlebot3_gazebo/models/turtlebot3_drl_world/goal_box')

        # Combine with model file
        self.entity_path = os.path.join(self.entity_dir_path, 'model.sdf')

        # Debugging logs
        print(f"Entity directory path: {self.entity_dir_path}")
        print(f"Entity path: {self.entity_path}")

        # Verify if the file exists
        if not os.path.isfile(self.entity_path):
            raise FileNotFoundError(f"Entity path does not exist: {self.entity_path}")

        self.entity = open(self.entity_path, 'r').read()
        self.entity_name = 'goal'`

**Comment by RaulFdzbis** [comment]
@RDaneelOlivav is right but I only needed to change **python3.8** to **python3.10** here:  https://github.com/tomasvr/turtlebot3_drlnav/blob/c16be2099e928ae1d2abbe523117590e637233c5/src/turtlebot3_drl/turtlebot3_drl/drl_gazebo/drl_gazebo.py#L48
