### ISSUE TITLE
No module named 'torch' error when opening the second terminal

### ISSUE THREAD

**Issue by liwenshulws** [tomasvr/turtlebot3_drlnav#8]
Hello, excuse me, I encountered an error while running the second terminal as follows:
Traceback (most recent call last):
File "/home/h3c/turbobot3_drlnav/install/turbobot3_drl/lib/turbobot3_drl/gazebo_goals", line 11, in<module>
Load_ Entry_ Point ('turblebot3 drl ',' console_scripts', 'gazebo_goals') ()
File "/usr/lib/python3/dist packages/pkg_resources/__init__. py", line 490, in load_ Entry_ Point
Return get_ Distribution (dist). load_ Entry_ Point (group, name)
File "/usr/lib/python3/dist packages/pkg_resources/__init__. py", line 2854, in load_ Entry_ Point
Return ep. load()
File "/usr/lib/python3/dist packages/pkg_resources/__init__. py", line 2445, in load
Return self. resolve ()
File "/usr/lib/python3/dist packages/pkg_resources/__init__. py", line 2451, in resolve
Module=__ Import__ (self. module_name, from list=['__name__ '], level=0)
File "/home/h3c/turbobot3_drlnav/build/tourlebot3_drl/tourlebot3_drl/drl_gazebo/drl_gazebo. py", line 35, in<module>
From DRL_ Environment.drl_ Environment import ARENA_ LENGTH, ARENA_ WIDTH, ENABLE_ DYNAMIC_ GOALS
File "/home/h3c/turbobot3_drlnav/build/turbobot3_drl/turbobot3_drl/drl_environment/drl_environment. py", line 36, in<module>
From Common import utilities as util
File "/home/h3c/turbobot3_drlnav/build/turbobot3_drl/turbobot3_drl/common/utilities. py", line 8, in<module>
Import torch
ModuleNotFoundError: No module named 'torch'
Why does this error still occur when I have installed Pytorch?

**Comment by liwenshulws** [comment]
Also, when installing pip3 install matplotlib pandas pyqtgraph=0.12.4 PyQt5=5.14.1 torch=1.10.0+cu113- f https://download.pytorch.org/whl/cu113/torch_stable.html This command will display the following error: ERROR: pip's dependency resolution does not currently take into account all the packages that are installed This behavior is the source of the following dependency conflicts

Torchaudio 0.12.0+cu116 requires torch=1.12.0, but you have torch 1.10.0+cu113 which is incompatible

Torchvision 0.13.0+cu113 requires torch=1.12.0, but you have torch 1.10.0+cu113 which is incompatible

Are these two errors related? How to solve it?

**Comment by tomasvr** [comment]
Are you using virtual environments? What does `pip3 show torch` output?

It would be a lot easier to use the docker image I provided, then you won't need to go through installing all of the dependencies yourself. I have provided instructions on how to get started with docker.

**Comment by NazishT** [comment]
try pip3 install torchvision==0.11.1

**Comment by cf-zhang** [comment]
Have you solved this problem? I also encountered the same problem

**Comment by zizhengu** [comment]
`export PYTHONPATH={path/to/your/torch/site-packages}:$PYTHONPATH`

e.g. `export PYTHONPATH=~/envs/torch1.10/lib/python3.8/site-packages:$PYTHONPATH`
